version: '3.3'

services:
  product_service:
    build: .
    network_mode: host
    ports:
      - 8080:8000
    environment:
      STAGE: beondiet
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://beondiet:beondiet@localhost:5001/beondiet

  db:
    image: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5001:5432
    environment:
      POSTGRES_USER: beondiet
      POSTGRES_PASSWORD: beondiet
