FROM python:3.7-slim as build

RUN mkdir -p /home/michal_kociszewski/flaskapi2/

COPY * /home/michal_kociszewski/flaskapi2/

WORKDIR /home/michal_kociszewski/flaskapi2/

RUN apt-get update && apt-get install -y cmake bison flex

RUN apt-get update && apt-get install -y build-essential

RUN PATH=$PATH:/pyroot/bin/make

RUN . ~/.bashrc

RUN pip install -r requirements.txt

CMD ["python", "-m", "flaskapi"]
